name: Authenticate with GITHUB_TOKEN

on:
  push:
    branches: [ "main", "main" ]
  workflow_dispatch:   # declanşează manual dacă vrei
jobs:
  token-demo:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create an issue via REST API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request POST \
            --url "https://api.github.com/repos/${{ github.repository }}/issues" \
            --header "Authorization: Bearer $GH_TOKEN" \
            --header "Content-Type: application/json" \
            --data '{"title": "Automated issue by GitHub Actions", "body": "This issue was created using GITHUB_TOKEN"}'
